version: '3.7'

services:
  db-pricefinder:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db-pg-pricefinder"
    restart: always
    volumes:
      - ./banco-pricefinder:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pricefinder
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: "app-pricefinder"
    volumes:
      - .:/usr/app
    restart: always
    depends_on:
      - db-pricefinder

volumes:
  banco-pricefinder:
