version: '3'

services:
  db-pricefinder:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db-pg-pricefinder"
    restart: always
    volumes:
      - ./banco-pricefinder:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

volumes: 
  banco-pricefinder: